
#
# Config.
#

url: http://blog.datasommelier.com
writeKey: M5FMIxFI3HXPl3vQp0aw2toQYSyRTgKb

#
# Bio.
#

name: Becky Jaimes
role: Data Sommelier
bio: "[Data Sommelier](https://www.datasomelier.com) Lorem ipsum dolor sit amet, consectetur adipiscing elit."


#
# Social.
#

twitter: 
github: TheBecky
email: becky@datasommelier.com
